CFLAGS=-lm

all: my_types numerics 27_degrees quadratic

my_types: my_types.c

numerics: numerics.c

27_degrees: 27_degrees.c

quadratic: quadratic.c

.PHONY: clean all

clean:
	rm my_types numerics 27_degrees
